// Node.js backend logic for Appwrite Function
const sdk = require("node-appwrite");

module.exports = async function(req, res) {
  const client = new sdk.Client()
    .setEndpoint(process.env.APPWRITE_ENDPOINT)
    .setProject(process.env.APPWRITE_PROJECT_ID)
    .setKey(process.env.APPWRITE_API_KEY);

  const payload = JSON.parse(req.body);
  const url = payload.url;

  const platform = url.includes("tiktok") ? "TikTok" :
                   url.includes("instagram") ? "Instagram" :
                   url.includes("youtube.com/shorts") ? "YT Shorts" :
                   "YouTube";

  const result = {
    platform,
    highlights: [
      { start: 10, end: 25, emoji: "🔥" },
      { start: 40, end: 55, emoji: "😱" }
    ],
    captions: "Auto-generated by Whisper",
    export: "Andrew Tate Style",
    deliveredTo: ["Telegram", "Zapier"]
  };

  return res.json({ success: true, ...result });
};
