name: Deploy to Appwrite
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy function
        uses: appwrite/github-actions-deploy-function@v2
        with:
          endpoint: https://cloud.appwrite.io/v1
          project:  viralayo-app
          key:      ${{ secrets.APPWRITE_API_KEY }}   # <- paste your new key there
          functionId: processVideoFn
          entrypoint: process-video.js
          code:      backend
