- name: Deploy function
  env:
    APPWRITE_ENDPOINT: https://cloud.appwrite.io/v1
    APPWRITE_PROJECT:  viralayo-app
    APPWRITE_KEY:      ${{ secrets.APPWRITE_API_KEY }}
  run: |
    cd backend
    tar -czf code.tar.gz process-video.js package.json

    # 1️⃣  configure the CLI
    appwrite client \
      --endpoint   "$APPWRITE_ENDPOINT" \
      --project-id "$APPWRITE_PROJECT" \
      --key        "$APPWRITE_KEY"

    # 2️⃣  deploy + activate latest build
    appwrite functions deploy \
      --function-id processVideoFn \
      --entrypoint  process-video.js \
      --code        code.tar.gz \
      --activate
